In [3]:
import pandas as pd
import io
import requests
import matplotlib.pyplot as plt
import torch
import torch.nn.functional as F

# Replace with the URL you copied
url = 'https://raw.githubusercontent.com/jvilchesf/Learning/main/Andrej_karpathy_videos/Makemore/names.txt'

response = requests.get(url)
words = response.text.splitlines()

In [4]:
chars = sorted(list(set("".join(words))))
stoi = {s:i+1 for i ,s in enumerate(chars)} 
stoi['.']= 0
itos = {i:s for s,i in stoi.items()}

In [39]:
#build dataset

block_size = 3
X , Y = [], []

for w in words[:5]: 
    #print(w)
    context = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        print(''.join(itos[i] for i in context), '---->', itos[ix])
        context = context[1:] + [ix]
    print("----------------------")

X = torch.tensor(X)
Y = torch.tensor(Y)

... ----> e
..e ----> m
.em ----> m
emm ----> a
mma ----> .
----------------------
... ----> o
..o ----> l
.ol ----> i
oli ----> v
liv ----> i
ivi ----> a
via ----> .
----------------------
... ----> a
..a ----> v
.av ----> a
ava ----> .
----------------------
... ----> i
..i ----> s
.is ----> a
isa ----> b
sab ----> e
abe ----> l
bel ----> l
ell ----> a
lla ----> .
----------------------
... ----> s
..s ----> o
.so ----> p
sop ----> h
oph ----> i
phi ----> a
hia ----> .
----------------------


In [63]:
C = torch.rand(27,2)
C[:13]

tensor([[0.5789, 0.2184],
        [0.5959, 0.2072],
        [0.6635, 0.7009],
        [0.8448, 0.6079],
        [0.1039, 0.5143],
        [0.7208, 0.6000],
        [0.2300, 0.8742],
        [0.3969, 0.3118],
        [0.9664, 0.9542],
        [0.9472, 0.3470],
        [0.0745, 0.0536],
        [0.3491, 0.3573],
        [0.6256, 0.3926]])

In [72]:
C[torch.tensor([0,0,15])]

tensor([[0.5789, 0.2184],
        [0.5789, 0.2184],
        [0.9696, 0.0598]])

In [73]:
X[6]

tensor([ 0,  0, 15])

In [75]:
C[X[5]]

tensor([[0.5789, 0.2184],
        [0.5789, 0.2184],
        [0.5789, 0.2184]])