In [3]:
import pandas as pd
import io
import requests
import matplotlib.pyplot as plt
import torch
import torch.nn.functional as F

# Replace with the URL you copied
url = 'https://raw.githubusercontent.com/jvilchesf/Learning/main/Andrej_karpathy_videos/Makemore/names.txt'

response = requests.get(url)
words = response.text.splitlines()

In [4]:
chars = sorted(list(set("".join(words))))
stoi = {s:i+1 for i ,s in enumerate(chars)} 
stoi['.']= 0
itos = {i:s for s,i in stoi.items()}

In [39]:
#build dataset

block_size = 3
X , Y = [], []

for w in words[:5]: 
    #print(w)
    context = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        print(''.join(itos[i] for i in context), '---->', itos[ix])
        context = context[1:] + [ix]
    print("----------------------")

X = torch.tensor(X)
Y = torch.tensor(Y)

... ----> e
..e ----> m
.em ----> m
emm ----> a
mma ----> .
----------------------
... ----> o
..o ----> l
.ol ----> i
oli ----> v
liv ----> i
ivi ----> a
via ----> .
----------------------
... ----> a
..a ----> v
.av ----> a
ava ----> .
----------------------
... ----> i
..i ----> s
.is ----> a
isa ----> b
sab ----> e
abe ----> l
bel ----> l
ell ----> a
lla ----> .
----------------------
... ----> s
..s ----> o
.so ----> p
sop ----> h
oph ----> i
phi ----> a
hia ----> .
----------------------


In [40]:
C = torch.rand(27,2)
C[:10]

tensor([[0.5688, 0.0591],
        [0.2872, 0.4386],
        [0.9051, 0.0599],
        [0.9763, 0.6234],
        [0.8823, 0.7476],
        [0.4313, 0.5563],
        [0.8199, 0.1229],
        [0.4339, 0.5943],
        [0.6375, 0.7506],
        [0.9699, 0.0620]])

In [41]:
C[5]

tensor([0.4313, 0.5563])

In [42]:
X.shape

torch.Size([32, 3])

In [43]:
C[X].shape

torch.Size([32, 3, 2])

In [44]:
dddddd

tensor([[0.5688, 0.0591],
        [0.2872, 0.4386],
        [0.9051, 0.0599],
        [0.9763, 0.6234],
        [0.8823, 0.7476],
        [0.4313, 0.5563],
        [0.8199, 0.1229],
        [0.4339, 0.5943],
        [0.6375, 0.7506],
        [0.9699, 0.0620],
        [0.4260, 0.7947],
        [0.0773, 0.4953],
        [0.2601, 0.7343],
        [0.2712, 0.7646],
        [0.2699, 0.8247],
        [0.0882, 0.4106],
        [0.3479, 0.6750],
        [0.0221, 0.5996],
        [0.0780, 0.6756],
        [0.8236, 0.0140],
        [0.8576, 0.1177],
        [0.4961, 0.5408],
        [0.3233, 0.0563],
        [0.4007, 0.2354],
        [0.8095, 0.4580],
        [0.5964, 0.6834],
        [0.2756, 0.2277]])